"""
Builds the complete secrets.toml for Streamlit Community Cloud.

    python exportar_secrets.py > secrets.toml

Reads the local configuration you already have working and prints the whole
block ready to paste into Settings -> Secrets:

    .env                            ANTHROPIC_API_KEY
    config/sheets.json              SPREADSHEET_ID
    config/google_credentials.json  [gcp_service_account]
    config/auth.yaml                [auth] (hashes only)

Doing this by hand is error-prone in exactly one place: the private_key
carries literal \\n sequences inside the string. Pasted as real line breaks,
Google auth fails with an unhelpful message. This escapes them correctly.

The output IS a secret. Never commit it; secrets.toml is in .gitignore.
"""

import json
import sys
from pathlib import Path

import yaml
from dotenv import dotenv_values

FALTA = []


def leer_json(path, etiqueta):
    p = Path(path)
    if not p.exists():
        FALTA.append(f"{etiqueta}: no existe {path}")
        return None
    return json.loads(p.read_text(encoding="utf-8"))


def escapar(valor):
    """TOML basic string: escape backslashes, quotes and real newlines."""
    return (str(valor)
            .replace("\\", "\\\\")
            .replace('"', '\\"')
            .replace("\n", "\\n")
            .replace("\r", ""))


salida = []

# --- Anthropic ------------------------------------------------------------
env = dotenv_values(".env")
key = env.get("ANTHROPIC_API_KEY")
if not key:
    FALTA.append("ANTHROPIC_API_KEY: no está en .env")
else:
    salida.append(f'ANTHROPIC_API_KEY = "{escapar(key)}"')

# --- Spreadsheet ----------------------------------------------------------
sheets = leer_json("config/sheets.json", "SPREADSHEET_ID")
if sheets and sheets.get("spreadsheet_id"):
    salida.append(f'SPREADSHEET_ID = "{escapar(sheets["spreadsheet_id"])}"')

# --- Google service account ----------------------------------------------
cred = leer_json("config/google_credentials.json", "gcp_service_account")
if cred:
    salida.append("\n[gcp_service_account]")
    orden = ["type", "project_id", "private_key_id", "private_key",
             "client_email", "client_id", "auth_uri", "token_uri",
             "auth_provider_x509_cert_url", "client_x509_cert_url",
             "universe_domain"]
    for campo in orden:
        if campo in cred:
            salida.append(f'{campo} = "{escapar(cred[campo])}"')

# --- Application users ----------------------------------------------------
auth_path = Path("config/auth.yaml")
if not auth_path.exists():
    FALTA.append("auth: no existe config/auth.yaml (corre python crear_auth.py)")
else:
    usuarios = yaml.safe_load(auth_path.read_text(encoding="utf-8")) or {}
    salida.append(f"\n# {len(usuarios)} users — password hashes only,"
                  f" no plaintext anywhere")
    salida.append("[auth]")
    for email, data in sorted(usuarios.items()):
        salida.append(f'\n["auth"."{email}"]')
        for campo in ("user_id", "name", "role", "team", "password"):
            salida.append(f'{campo} = "{escapar(data.get(campo, ""))}"')

# --- Result ---------------------------------------------------------------
if FALTA:
    print("FALTAN DATOS — no se generó nada:", file=sys.stderr)
    for f in FALTA:
        print(f"  - {f}", file=sys.stderr)
    sys.exit(1)

print("\n".join(salida))

print("\n# Generated by exportar_secrets.py — paste into Streamlit Cloud:",
      file=sys.stderr)
print("#   Settings -> Secrets", file=sys.stderr)
print("# This file is a secret. It is in .gitignore; keep it that way.",
      file=sys.stderr)